# Generated by Django 5.2.5 on 2025-08-11 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_slider'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actualite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='blog/')),
                ('date_pub', models.DateField(auto_now_add=True)),
                ('lien', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
