# Generated by Django 5.2.5 on 2025-08-11 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_actualite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='debit',
        ),
        migrations.RemoveField(
            model_name='service',
            name='is_active',
        ),
        migrations.AddField(
            model_name='service',
            name='badge',
            field=models.CharField(blank=True, help_text='Ex: Populaire, Service+, 24/7', max_length=30),
        ),
        migrations.AddField(
            model_name='service',
            name='badge_color',
            field=models.CharField(blank=True, help_text='Ex: badge-promo', max_length=30),
        ),
        migrations.AddField(
            model_name='service',
            name='icone',
            field=models.CharField(default='bi-wifi', help_text="Nom de l’icône Bootstrap ex: 'bi-wifi'", max_length=50),
        ),
        migrations.AddField(
            model_name='service',
            name='ordre',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='service',
            name='prix',
            field=models.CharField(default='À définir', max_length=50),
        ),
    ]
