# Generated by Django 5.2.5 on 2025-08-11 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_service_debit_remove_service_is_active_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='zonecouverture',
            old_name='quartier',
            new_name='nom',
        ),
        migrations.RemoveField(
            model_name='zonecouverture',
            name='disponible',
        ),
        migrations.RemoveField(
            model_name='zonecouverture',
            name='ville',
        ),
        migrations.AddField(
            model_name='zonecouverture',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
