# Generated by Django 5.2.5 on 2025-08-12 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_quartier_zonecouverture_nom_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='logo/')),
                ('alt', models.CharField(default='Logo SkyConnect', max_length=100)),
            ],
        ),
    ]
