# Generated by Django 5.2.5 on 2025-08-12 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_service_prix'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='description',
        ),
        migrations.AddField(
            model_name='service',
            name='description1',
            field=models.CharField(blank=True, max_length=255, verbose_name='Description courte'),
        ),
        migrations.AddField(
            model_name='service',
            name='description2',
            field=models.CharField(blank=True, max_length=255, verbose_name='Avantage 1'),
        ),
        migrations.AddField(
            model_name='service',
            name='description3',
            field=models.CharField(blank=True, max_length=255, verbose_name='Avantage 2'),
        ),
        migrations.AddField(
            model_name='service',
            name='description4',
            field=models.CharField(blank=True, max_length=255, verbose_name='Avantage 3'),
        ),
    ]
