# Generated by Django 5.2.5 on 2025-08-14 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_service_description_service_description1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='zonecouverture',
            name='cx',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='zonecouverture',
            name='cy',
            field=models.FloatField(default=0),
        ),
    ]
