# Generated by Django 5.2.5 on 2025-08-14 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_zonecouverture_cx_zonecouverture_cy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zonecouverture',
            name='cx',
        ),
        migrations.RemoveField(
            model_name='zonecouverture',
            name='cy',
        ),
    ]
