# Generated by Django 5.2.5 on 2025-08-19 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_zonecouverture_cx_remove_zonecouverture_cy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commune',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.RenameField(
            model_name='zonecouverture',
            old_name='nom',
            new_name='region',
        ),
        migrations.AlterField(
            model_name='actualite',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='zonecouverture',
            name='commune',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='core.commune'),
            preserve_default=False,
        ),
    ]
