# Generated by Django 5.2.5 on 2025-08-19 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_commune_rename_nom_zonecouverture_region_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zonecouverture',
            name='commune',
        ),
        migrations.AddField(
            model_name='zonecouverture',
            name='communes',
            field=models.ManyToManyField(related_name='zones', to='core.commune'),
        ),
    ]
