# Generated by Django 5.2.5 on 2025-08-20 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_zonecouverture_commune_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActualiteImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='blog/')),
                ('alt', models.CharField(blank=True, max_length=100)),
                ('actualite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.actualite')),
            ],
        ),
    ]
