# Generated by Django 5.2.5 on 2025-08-20 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_actualiteimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actualite',
            name='image',
        ),
    ]
